### ISSUE TITLE
Package for lower frequencies than 1e-04

### ISSUE THREAD

**Issue by vanessapitz** [cran/genpwr#1]
This is such a useful package!! Does it work similar to the GAS calculator? I was wondering if you're planning on implementing lower frequencies than 1e-04? At least for me this is the lowest possible shown. It would be useful to look at even rarer variants too. 
Best
Vanessa

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
